services:
  zk-1:
    image: zookeeper:3.9.4
    container_name: zk-1
    hostname: zk-1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: "server.1=zk-1:2888:3888 server.2=zk-2:2888:3888 server.3=zk-3:2888:3888"

  zk-2:
    image: zookeeper:3.9.4
    container_name: zk-2
    hostname: zk-2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: "server.1=zk-1:2888:3888 server.2=zk-2:2888:3888 server.3=zk-3:2888:3888"

  zk-3:
    image: zookeeper:3.9.4
    container_name: zk-3
    hostname: zk-3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: "server.1=zk-1:2888:3888 server.2=zk-2:2888:3888 server.3=zk-3:2888:3888"